baseURL = "https://yoginarasimha.github.io"
defaultContentLanguage = "ch"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
theme = "lugo"
languageCode = "de-ch"
title = "Yogi Narasimha"
