name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.2  # Neueste Hugo Version zum Zeitpunkt 2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dart Sass
        run: |
          curl -L https://github.com/sass/dart-sass/releases/download/1.63.4/dart-sass-1.63.4-linux-x64.tar.gz | tar xz
          sudo mv dart-sass/sass /usr/local/bin/sass
          sudo chmod 755 /usr/local/bin/sass

      - name: Install Hugo CLI
        run: |
          wget -qO- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xz -C ${{ runner.temp }}
          sudo mv ${{ runner.temp }}/hugo /usr/local/bin/hugo

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build website
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

